[package]
name = "slog-filerotate"
version = "0.1.0"
authors = ["luciferchn@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libflate = "1.0.3"

